import type { Product } from "@/features/products/types/product.types";

export const mockProducts: Product[] = [
  {
    id: "fleur-de-lune",
    name: "Fleur de Lune",
    description: "A luminous floral composition of jasmine and white musk.",
    notes: "Floral / Jasmine & White Musk",
    price: 195,
    images: ["/images/products/fleur-de-lune.png"],
    category: "pure-extractions",
    scentFamily: "floral",
    occasion: "personal-use",
    options: [],
  },
  {
    id: "santal-parchment",
    name: "Santal Parchment",
    description:
      "Santal Parchment wraps around the skin like vintage vellum paper. It opens with bright top notes, shifting to clean papyrus and warm, rich sandalwood that dry down into dry cardamom and amber.",
    notes: "Woody / Sandalwood & Cardamom",
    price: 220,
    images: [
      "/images/products/santal-parchment/hero.png",
      "/images/products/santal-parchment/thumb-0.png",
      "/images/products/santal-parchment/thumb-1.png",
      "/images/products/santal-parchment/thumb-2.png",
    ],
    category: "pure-extractions",
    scentFamily: "woody",
    occasion: "evening",
    options: [],
    volumes: [
      { label: "30 ml", price: 140 },
      { label: "50 ml", price: 180 },
      { label: "100 ml", price: 220 },
    ],
    scentFamilyLabel: "Woody",
    occasionLabel: "Evening",
    availabilityLabel: "Available in Atelier",
    anatomy: {
      description:
        "Santal Parchment wraps around the skin like vintage vellum paper. It opens with bright top notes, shifting to clean papyrus and warm, rich sandalwood that dry down into dry cardamom and amber.",
      top: "Sicilian Bergamot, Pink Pepper",
      heart: "Egyptian Jasmine Sambac, Papyrus",
      base: "West Indian Sandalwood, Cardamom, Amber",
    },
    relatedIds: [
      "fleur-de-lune",
      "noir-cocoon",
      "sol-dor",
      "rose-absolute",
    ],
  },
  {
    id: "noir-cocoon",
    name: "Noir Cocoon",
    description: "An oriental blend of tobacco and amber.",
    notes: "Oriental / Tobacco & Amber",
    price: 240,
    images: ["/images/products/noir-cocoon.png"],
    category: "private-reserve",
    scentFamily: "oriental",
    occasion: "wedding",
    options: [],
  },
  {
    id: "sol-dor",
    name: "Sol d'Or",
    description: "A fresh coastal blend of bergamot and sea salt.",
    notes: "Fresh / Bergamot & Sea Salt",
    price: 185,
    images: ["/images/products/sol-dor.png"],
    category: "pure-extractions",
    scentFamily: "fresh",
    occasion: "personal-use",
    options: [],
  },
  {
    id: "atelier-oud",
    name: "Atelier Oud",
    description: "Rich oud deepened with saffron.",
    notes: "Woody / Rich Oud & Saffron",
    price: 310,
    images: ["/images/products/atelier-oud.png"],
    category: "atelier-oils",
    scentFamily: "woody",
    occasion: "gift-sets",
    options: [],
  },
  {
    id: "rose-absolute",
    name: "Rose Absolute",
    description: "Damask rose balanced with cedar.",
    notes: "Floral / Damask Rose & Cedar",
    price: 205,
    images: ["/images/products/rose-absolute.png"],
    category: "private-reserve",
    scentFamily: "floral",
    occasion: "birthday",
    options: [],
  },
];
